# Generated by Django 4.1.6 on 2023-03-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_product_alter_listings_auction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auctions',
            new_name='Auction',
        ),
        migrations.RenameModel(
            old_name='AuctionComments',
            new_name='AuctionComment',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.RenameModel(
            old_name='ListingComments',
            new_name='ListingComment',
        ),
    ]
