# Generated by Django 4.1.6 on 2023-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auctions_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='name',
            field=models.CharField(default='Unsigned', max_length=64),
        ),
    ]
