# Generated by Django 4.1.6 on 2023-03-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.auctiontype'),
        ),
    ]
