# Generated by Django 4.1.6 on 2023-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctiontype_alter_auction_auction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctiontype',
            old_name='type',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
