# Generated by Django 4.1.6 on 2023-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_type_auctiontype_type_name_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
