# Generated by Django 4.1.6 on 2023-03-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionComment',
        ),
    ]
