# Generated by Django 4.2 on 2023-05-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiontype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
